name: yolo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # required
  - numpy
  - pandas
  - Pillow
  - torch
  - torchvision

  # optional
  - ipykernel # to run notebooks

  # code checks
  - black